chore: bump glob to 9.3.5
electron/asar pull request #304
Opened 2024-03-07 20:01 UTC by theogravity

This updates the project to use `glob@9.3.5` (not using glob@10 as that looks to be ESM-only and this project does not have ESM support).

The reason for updating `glob` is older versions of `glob` uses `inflight`, which has a [medium-level vulun](https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116) that triggers our Vanta SOC2 compliance monitoring for security issues.

2024-03-07 20:03 UTC, theogravity commented on lib/crawlfs.js
> +  let crawled = await glob(dir, options || {})
I did try `async function (dir, options = {})` but tests would fail with that.

2024-03-07 20:39 UTC, dsanders11 requested changes
This needs to be marked as a breaking change (add `BREAKING CHANGE: ...` in the body of the commit message) so that it would trigger a v4 release on merge.

If we're going to do a breaking change we probably want to just jump to Node v18 rather than v16 which is already EOL.

But I'm not sure if we consider this worth introducing a breaking change to address.

2024-03-07 20:40 UTC, dsanders11 commented
Tests appear to be failing on Windows.

2024-03-07 20:58 UTC, theogravity commented
@dsanders11 Addressed the comments.

2024-03-07 21:34 UTC, erickzhao requested changes
I'm not sure if this is a complete solution for the purposes of resolving security scannner warnings because we still have dependencies to `glob@7.2.0, glob@^7.0.5, glob@^7.1.3` as per the `yarn.lock` file via various transient dependencies.

2024-03-07 21:35 UTC, theogravity commented
> I'm not sure if this is a complete solution for the purposes of resolving security scanner warnings because we still have dependencies to `glob@7.2.0, glob@^7.0.5, glob@^7.1.3` as per the `yarn.lock` file via various transient dependencies.

The transients are only on devDeps though. At least for our scanner, it only cares about deps for node_module installs.

2024-03-11 16:50 UTC, ckerr approved these changes
The code changes LGTM, approving on that part.

@dsanders11 is right about the node bump / breaking change question. I don't have a strong opinion there except that we probably shouldn't depend on EOL packages  

@erickzhao is right that there are still other devdep vectors do depend on old versions of glob, but fixing one is better than fixing zero :man_shrugging:

2024-07-21 14:12 UTC, hallelk commented
bump

2024-08-12 00:05 UTC, closed without merging