Move @types/glob to devDependencies
electron/asar pull request #332
Opened 2024-10-11 15:18 UTC by Hinton

Type dependencies should be dev dependencies, that way they won't affect downstream packages.

This change seems to have no negative impacts on building or running tests in the project.

2024-10-11 15:37 UTC, MarshallOfSound requested changes
This is semantically incorrect and will also cause issues as we do use glob types in exported types

2024-10-24 12:56 UTC, aaclayton commented
This is causing big problems for us too. Our documentation builds (typedoc) are completely failing because of this unless we do clumsy manual workarounds.

2024-10-24 14:11 UTC, erikian commented
> Isn't glob now natively in typescript anyways? Why is an extra types package needed?

It is, but at this moment `@electron/asar` [supports Node 10.12.0 and up](https://github.com/electron/asar/blob/b7730638891726666776c68116b51043d39424ef/package.json#L14-L16), while `glob` [only became native TS on v9](https://github.com/isaacs/node-glob/blob/08958fa38ac1a59f82b0cf912208ec9548fb28cc/changelog.md#90) which requires Node 16. [We do have plans](https://github.com/electron/governance/tree/13acc859f71d524e9e67b748741d1c9842079ce1/wg-ecosystem#nodejs-upgrade-policy) to upgrade all ecosystem packages to a newer Node version as soon as support for `require`ing ESM graphs makes it into Node LTS, but I'm afraid we probably won't be updating `glob` until then unless we need to land another breaking change in the meantime.

That being said, based on https://github.com/electron/asar/pull/267 / https://github.com/electron/asar/pull/268, looks like we've solved this in the past by inlining the types, and that got lost when `@electron/asar` was rewritten in TS in #320, so we can probably just re-land the changes from #268 – I'll open a PR for that in a minute.

2024-10-25 01:52 UTC, erikian commented
Fixed in #336

2024-10-25 01:52 UTC, closed without merging